# Generated by Django 4.1.7 on 2023-07-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/menus/'),
        ),
    ]
