# Generated by Django 4.1.7 on 2023-07-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
    ]
