# Generated by Django 4.1.7 on 2023-08-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_category_customer_remove_menu_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='apis.restaurant'),
        ),
    ]
