# Generated by Django 4.1.7 on 2023-11-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_menu_description_menu_restaurant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
