# Generated by Django 4.1.7 on 2023-11-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_restaurant_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menurestaurant',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='menurestaurant',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.AlterModelTable(
            name='food',
            table='food',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='menurestaurant',
            table='menu_restaurant',
        ),
    ]
